package pl.strojecki;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LandRegisterConst {

    public static List<Integer> createWeightList() {
        List<Integer> result = new ArrayList<>();
        result.add(1);
        result.add(3);
        result.add(7);
        result.add(1);
        result.add(3);
        result.add(7);
        result.add(1);
        result.add(3);
        result.add(7);
        result.add(1);
        result.add(3);
        result.add(7);

        return result;
    }

    public static Map<Character, Integer> createConversionMap() {
        Map<Character, Integer> result = new HashMap<Character, Integer>();
        result.put('0', 0);
        result.put('1', 1);
        result.put('2', 2);
        result.put('3', 3);
        result.put('4', 4);
        result.put('5', 5);
        result.put('6', 6);
        result.put('7', 7);
        result.put('8', 8);
        result.put('9', 9);
        result.put('X', 10);
        result.put('A', 11);
        result.put('B', 12);
        result.put('C', 13);
        result.put('D', 14);
        result.put('E', 15);
        result.put('F', 16);
        result.put('G', 17);
        result.put('H', 18);
        result.put('I', 19);
        result.put('J', 20);
        result.put('K', 21);
        result.put('L', 22);
        result.put('M', 23);
        result.put('N', 24);
        result.put('O', 25);
        result.put('P', 26);
        result.put('R', 27);
        result.put('S', 28);
        result.put('T', 29);
        result.put('U', 30);
        result.put('W', 31);
        result.put('Y', 32);
        result.put('Z', 33);

        return result;
    }

    public static Map<String, String> createCourts() {
        Map<String, String> result = new HashMap<>();
        result.put("WL1A", "Aleksandrów Kujawski");
        result.put("SU1A", "Augustów");
        result.put("OL1Y", "Bartoszyce");
        result.put("PT1B", "Bełchatów");
        result.put("KA1B", "Będzin");
        result.put("LU1B", "Biała podlaska");
        result.put("RA2G", "Białobrzegi");
        result.put("KO1B", "Białogard");
        result.put("BI1B", "Białystok");
        result.put("BB1B", "Bielsko-Biała");
        result.put("BI1P", "Bielsk Podlaski");
        result.put("ZA1B", "Biłgoraj");
        result.put("OL1B", "Biskupiec");
        result.put("TR1O", "BochniaR1O");
        result.put("JG1B", "Bolesławiec");
        result.put("EL1B", "Braniewo");
        result.put("TO1B", "Brodnica");
        result.put("OP1B", "Brzeg");
        result.put("TR1B", "Brzesko");
        result.put("LD1B", "Brzeziny");
        result.put("KS1B", "Brzozów");
        result.put("KI1B", "Busko Zdrój");
        result.put("BY1B", "Bydgoszcz");
        result.put("KA1Y", "Bytom");
        result.put("SL1B", "Bytów");
        result.put("LU1C", "Chełm");
        result.put("TO1C", "Chełmno");
        result.put("PO1H", "Chodzież");
        result.put("SL1C", "Chojnice");
        result.put("KA1C", "Chorzów");
        result.put("SZ1C", "Choszczno");
        result.put("KR1C", "Chrzanów");
        result.put("PL1C", "Ciechanów");
        result.put("BB1C", "Cieszyn");
        result.put("PO2T", "Czarnków");
        result.put("KR1K", "Czernichów");
        result.put("CZ1C", "Częstochowa");
        result.put("SL1Z", "Człuchów");
        result.put("KA1D", "Dąbrowa Górnicza");
        result.put("TR1D", "Dąbrowa Tarnowska");
        result.put("RZ1D", "Dębica");
        result.put("KR2Y", "Dobczyce");
        result.put("KO1D", "Drawsko Pomorskie");
        result.put("EL1D", "Działdowo");
        result.put("SW1D", "Dzierżoniów");
        result.put("EL1E", "Elbląg");
        result.put("OL1E", "Ełk");
        result.put("SI1G", "Garwolin");
        result.put("GD1G", "Gdańsk");
        result.put("GD1Y", "Gdynia");
        result.put("OL1G", "Giżycko");
        result.put("GL1G", "Gliwice");
        result.put("LE1G", "Głogów");
        result.put("OP1G", "Głubczyce");
        result.put("PO1G", "Gniezno");
        result.put("SZ1O", "Goleniów");
        result.put("TO1G", "Golub-Dobrzyń");
        result.put("NS1G", "Gorlice");
        result.put("GW1G", "Gorzów Wielkopolski");
        result.put("PL1G", "Gostynin");
        result.put("PO1Y", "Gostyń");
        result.put("LM1G", "Grajewo");
        result.put("WA1G", "Grodzisk Mazowiecki");
        result.put("PO1S", "Grodzisk Wlkp.");
        result.put("RA1G", "Grójec");
        result.put("TO1U", "Grudziądz");
        result.put("SZ1G", "Gryfice");
        result.put("SZ1Y", "Gryfino");
        result.put("ZG2K", "Gubin");
        result.put("BI2P", "Hajnówka");
        result.put("ZA1H", "Hrubieszów");
        result.put("EL1I", "Iława");
        result.put("BY1I", "Inowrocław");
        result.put("ZA1J", "Janów Lubelski");
        result.put("KZ1J", "Jarocin");
        result.put("PR1J", "Jarosław");
        result.put("KS1J", "Jasło");
        result.put("GL1J", "Jastrzębie-Zdrój");
        result.put("LE1J", "Jawor");
        result.put("KA1J", "Jaworzno");
        result.put("JG1J", "Jelenia Góra");
        result.put("KI1J", "Jędrzejów");
        result.put("KZ1A", "Kalisz");
        result.put("JG1K", "Kamienna Góra");
        result.put("SZ1K", "Kamień Pomorski");
        result.put("GD1R", "Kartuzy");
        result.put("KA1K", "Katowice");
        result.put("KI1I", "Kazimierza wielka");
        result.put("OP1K", "Kędzierzyn-koźle");
        result.put("KZ1E", "Kępno");
        result.put("OL1K", "Kętrzyn");
        result.put("KR2E", "Kęty");
        result.put("KI1L", "Kielce");
        result.put("OP1U", "Kluczbork");
        result.put("CZ2C", "Kłobuck");
        result.put("SW1K", "Kłodzko");
        result.put("TB1K", "Kolbuszowa");
        result.put("KO1L", "Kołobrzeg");
        result.put("KN1K", "Koło");
        result.put("KN1N", "Konin");
        result.put("KI1K", "Końskie");
        result.put("KO1K", "Koszalin");
        result.put("PO1K", "Kościan");
        result.put("GD1E", "Kościerzyna");
        result.put("RA1K", "Kozienice");
        result.put("KR1P", "Kraków");
        result.put("ZA1K", "Krasnystaw");
        result.put("LU1K", "Kraśnik");
        result.put("KS1K", "Krosno");
        result.put("ZG1K", "Krosno Odrzańskie");
        result.put("KZ1R", "Krotoszyn");
        result.put("KR2K", "Krzeszowice");
        result.put("LD1K", "Kutno");
        result.put("GD1I", "Kwidzyn");
        result.put("WA1L", "Legionowo");
        result.put("LE1L", "Legnica");
        result.put("KS1E", "Lesko");
        result.put("PO1L", "Leszno");
        result.put("RZ1E", "Leżajsk");
        result.put("SL1L", "Lębork");
        result.put("OL1L", "Lidzbark Warmiński");
        result.put("NS1L", "Limanowa");
        result.put("WL1L", "Lipno");
        result.put("RA1L", "Lipsko");
        result.put("PR1L", "Lubaczów");
        result.put("JG1L", "Lubań");
        result.put("LU1A", "Lubartów");
        result.put("LE1U", "Lubin");
        result.put("CZ1L", "Lubliniec");
        result.put("LU1I", "Lublin");
        result.put("JG1S", "Lwówek Śląski");
        result.put("RZ1A", "Łańcut");
        result.put("SR1L", "Łask");
        result.put("LD1Y", "Łęczyca");
        result.put("SZ1L", "Łobez");
        result.put("LM1L", "Łomża");
        result.put("SI2S", "Łosice");
        result.put("LD1O", "Łowicz");
        result.put("LD1M", "Łódź");
        result.put("LU1U", "Łuków");
        result.put("GD1M", "Malbork");
        result.put("SL1M", "Miastko");
        result.put("KR1M", "Miechów");
        result.put("TB1M", "Mielec");
        result.put("PO2A", "Międzychód");
        result.put("GW1M", "Międzyrzecz");
        result.put("KA1M", "Mikołów");
        result.put("WR1M", "Milicz");
        result.put("SI1M", "Mińsk Mazowiecki");
        result.put("PL1M", "Mława");
        result.put("BY1M", "Mogilno");
        result.put("EL2O", "Morąg");
        result.put("OL1M", "Mrągowo");
        result.put("NS2L", "Mszana Dolna");
        result.put("NS1M", "Muszyna");
        result.put("KA1L", "Mysłowice");
        result.put("CZ1M", "Myszków");
        result.put("KR1Y", "Myślenice");
        result.put("SZ1M", "Myślibórz");
        result.put("BY1N", "Nakło nad Notecią");
        result.put("OL1N", "Nidzica");
        result.put("KR2I", "Niepołomice");
        result.put("TB1N", "Nisko");
        result.put("SW2K", "Nowa Ruda");
        result.put("ZG1N", "Nowa Sól");
        result.put("EL1N", "Nowe Miasto Lubawskie");
        result.put("GD2M", "Nowy Dwór Gdański");
        result.put("WA1N", "Nowy Dwór Mazowiecki");
        result.put("NS1S", "Nowy Sącz");
        result.put("NS1T", "Nowy Targ");
        result.put("PO1N", "Nowy Tomyśl");
        result.put("OP1N", "Nysa");
        result.put("PO1O", "Oborniki");
        result.put("OL1C", "Olecko");
        result.put("OP1L", "Olesno");
        result.put("WR1E", "Oleśnica");
        result.put("KR1O", "Olkusz");
        result.put("OL1O", "Olsztyn");
        result.put("WR1O", "Oława");
        result.put("KI1T", "Opatów");
        result.put("PT1O", "Opoczno");
        result.put("LU1O", "Opole Lubelskie");
        result.put("OP1O", "Opole");
        result.put("OS1O", "Ostrołęka");
        result.put("KI1O", "Ostrowiec Świętokrzyski");
        result.put("EL1O", "Ostróda");
        result.put("OS1M", "Ostrów Mazowiecka");
        result.put("KZ1W", "Ostrów Wielkopolski");
        result.put("KZ1O", "Ostrzeszów");
        result.put("KR1E", "Oświęcim");
        result.put("WA1O", "Otwock");
        result.put("LD1P", "Pabianice");
        result.put("SR2W", "Pajęczno");
        result.put("WA1I", "Piaseczno");
        result.put("PO1I", "Piła");
        result.put("KI1P", "Pińczów");
        result.put("RA2Z", "Pionki");
        result.put("PT1P", "Piotrków Trybunalski");
        result.put("OL1P", "Pisz");
        result.put("KZ1P", "Pleszew");
        result.put("PL1P", "Płock");
        result.put("PL1L", "Płońsk");
        result.put("SR2L", "Poddębice");
        result.put("SZ2S", "Police");
        result.put("PO1P", "Poznań (V)");
        result.put("PO2P", "Poznań (VI)");
        result.put("KR1H", "Proszowice");
        result.put("OP1P", "Prudnik");
        result.put("WA1P", "Pruszków");
        result.put("OS1P", "Przasnysz");
        result.put("PR1P", "Przemyśl");
        result.put("PR1R", "Przeworsk");
        result.put("RA1P", "Przysucha");
        result.put("KA1P", "Pszczyna");
        result.put("GD2W", "Puck");
        result.put("LU1P", "Puławy");
        result.put("OS1U", "Pułtusk");
        result.put("SZ2T", "Pyrzyce");
        result.put("GL1R", "Racibórz");
        result.put("RA1R", "Radom");
        result.put("PT1R", "Radomsko");
        result.put("WL1R", "Radziejów");
        result.put("LU1R", "Radzyń Podlaski");
        result.put("LD1R", "Rawa Mazowiecka");
        result.put("PO1R", "Rawicz");
        result.put("RZ1R", "Ropczyce");
        result.put("GL1S", "Ruda Śląska");
        result.put("GL1Y", "Rybnik");
        result.put("LU1Y", "Ryki");
        result.put("WL1Y", "Rypin");
        result.put("RZ1Z", "Rzeszów");
        result.put("KI1S", "Sandomierz");
        result.put("KS1S", "Sanok");
        result.put("SU1N", "Sejny");
        result.put("BY2T", "Sępólno Krajeńskie");
        result.put("SI1S", "Siedlce");
        result.put("KA1I", "Siemianowice Śląskie");
        result.put("BI3P", "Siemiatycze");
        result.put("PR2R", "Sieniawa");
        result.put("SR1S", "Sieradz");
        result.put("PL1E", "Sierpc");
        result.put("KR2P", "Skała");
        result.put("KI1R", "Skarżysko-Kamienna");
        result.put("KR3I", "Skawina");
        result.put("LD1H", "Skierniewice");
        result.put("KO1E", "Sławno");
        result.put("KR1S", "Słomniki");
        result.put("GW1S", "Słubice");
        result.put("KN1S", "Słupca");
        result.put("SL1S", "Słupsk");
        result.put("PL1O", "Sochaczew");
        result.put("SI1P", "Sokołów Podlaski");
        result.put("BI1S", "Sokółka");
        result.put("GD1S", "Sopot");
        result.put("KA1S", "Sosnowiec");
        result.put("TB1S", "Stalowa Wola");
        result.put("KI1H", "Starachowice");
        result.put("SZ1T", "Stargard Szczeciński");
        result.put("GD1A", "Starogard Gdański");
        result.put("KI1A", "Staszów");
        result.put("GW1K", "Strzelce Krajeńskie");
        result.put("OP1S", "Strzelce Opolskie");
        result.put("WR1T", "Strzelin");
        result.put("RZ1S", "Strzyżów");
        result.put("KR1B", "Sucha Beskidzka");
        result.put("ZG2S", "Sulechów");
        result.put("GW1U", "Sulęcin");
        result.put("SU1S", "Suwałki");
        result.put("PO1A", "Szamotuły");
        result.put("KO1I", "Szczecinek");
        result.put("SZ1S", "Szczecin");
        result.put("OL1S", "Szczytno");
        result.put("GD2I", "Sztum");
        result.put("BY1U", "Szubin");
        result.put("RA1S", "Szydłowiec");
        result.put("PO1M", "Śrem");
        result.put("WR1S", "Środa Śląska");
        result.put("PO1D", "Środa Wlkp.");
        result.put("SW1S", "Świdnica");
        result.put("KO2B", "Świdwin");
        result.put("ZG1S", "Świebodzin");
        result.put("BY1S", "Świecie");
        result.put("SZ1W", "Świnoujście");
        result.put("TB1T", "Tarnobrzeg");
        result.put("GL1T", "Tarnowskie Góry");
        result.put("TR1T", "Tarnów");
        result.put("GD1T", "Tczew");
        result.put("ZA1T", "Tomaszów Lubelski");
        result.put("PT1T", "Tomaszów Mazowiecki");
        result.put("TO1T", "Toruń");
        result.put("PO1T", "Trzcianka");
        result.put("WR1W", "Trzebnica");
        result.put("BY1T", "Tuchola");
        result.put("TR2T", "Tuchów");
        result.put("KN1T", "Turek");
        result.put("KA1T", "Tychy");
        result.put("RZ2Z", "Tyczyn");
        result.put("KS2E", "Ustrzyki Dolne");
        result.put("KR1W", "Wadowice");
        result.put("SW1W", "Wałbrzych");
        result.put("KO1W", "Wałcz");
        result.put("WA3M", "Warszawa (IX)");
        result.put("WA1M", "Warszawa (VI)");
        result.put("WA2M", "Warszawa (VII)");
        result.put("WA4M", "Warszawa (X)");
        result.put("WA5M", "Warszawa (XIII)");
        result.put("WA6M", "Warszawa (XV)");
        result.put("TO1W", "Wąbrzeźno");
        result.put("PO1B", "Wągrowiec");
        result.put("GD1W", "Wejherowo");
        result.put("OL2G", "Węgorzewo");
        result.put("SI1W", "Węgrów");
        result.put("KR1I", "Wieliczka");
        result.put("SR1W", "Wieluń");
        result.put("WL1W", "Włocławek");
        result.put("LU1W", "Włodawa");
        result.put("KI1W", "Włoszczowa");
        result.put("GL1W", "Wodzisław Śląski");
        result.put("PO1E", "Wolsztyn");
        result.put("WA1W", "Wołomin");
        result.put("WR1L", "Wołów");
        result.put("WR1K", "Wrocław");
        result.put("PO1F", "Września");
        result.put("ZG1W", "Wschowa");
        result.put("PO2H", "Wyrzysk");
        result.put("LM1W", "Wysokie Mazowieckie");
        result.put("OS1W", "Wyszków");
        result.put("GL1Z", "Zabrze");
        result.put("NS1Z", "Zakopane");
        result.put("LM1Z", "Zambrów");
        result.put("ZA1Z", "Zamość");
        result.put("CZ1Z", "Zawiercie");
        result.put("SW1Z", "Ząbkowice Śląskie");
        result.put("SR1Z", "Zduńska Wola");
        result.put("LD1G", "Zgierz");
        result.put("JG1Z", "Zgorzelec");
        result.put("ZG1E", "Zielona Góra");
        result.put("LE1Z", "Złotoryja");
        result.put("PO1Z", "Złotów");
        result.put("RA1Z", "Zwoleń");
        result.put("ZG1G", "Żagań");
        result.put("ZG1R", "Żary");
        result.put("BY1Z", "Żnin");
        result.put("GL1X", "Żory");
        result.put("PL2M", "Żuromin");
        result.put("PL1Z", "Żyrardów");
        result.put("BB1Z", "Żywiec");

        return result;
    }

}
